# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  productsapi:
    image: productsapi
    build:
      context: .
      dockerfile: products.api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - produtos-network
    depends_on:
      - "cap-postgres"

  
  cap-postgres:
    image: postgres
    container_name: cap-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produtos
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - produtos-network

volumes:
  postgres-volume:
    driver: local

networks: 
  produtos-network:
    driver: bridge